### PR TITLE
Zeal Docsets

### PR DESCRIPTION
**Pull request by maxd-nordic**

### CODE REVIEW

**Comment by maxd-nordic** [comment]
# How to test
1. Install [zeal](https://zealdocs.org/Zeal) (e.g. `apt install zeal`)
2. Install standard docsets like C or Python under Tools -> Docsets
3. Download the docsets artifact from https://github.com/maxd-nordic/sdk-nrf/actions/runs/4128541715/
4. Unpack the *.docset folders to `~/.local/share/Zeal/Zeal/docsets` or `%APPDATA%\Local\Zeal\Zeal\docsets`
5. Restart Zeal

**Comment by maxd-nordic** [comment]
todo: fix https://github.com/executablebooks/sphinx-tabs which cannot be clicked in zeal

**Comment by maxd-nordic** [comment]
todo: filter out group__* index entries

**Comment by maxd-nordic** [comment]
todo: fix index pages

**Comment by maxd-nordic** [comment]
todo: fork and simplify https://github.com/nrfconnect/doc-sphinx-ncs-theme/tree/main/sphinx_ncs_theme

**Comment by maz3max** [comment]
Tabs without JS: https://codepen.io/dhs/pen/zYErrW

**Pull request closed without merging**
